services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    networks:
      - flask-network
  web:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=operator
      - MYSQL_PASSWORD=operator
      - MYSQL_DATABASE=security
    networks:
      - flask-network
  db:
    image: mysql:8.0
    container_name: flask-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX3edc
      MYSQL_DATABASE: security
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./security.sql:/docker-entrypoint-initdb.d/security.sql
    networks:
      - flask-network

volumes:
  mysql-data:  # MySQL data persistence

networks:
  flask-network:
    driver: bridge